// export const dummyInitialAppState = {
//     prompt: 'dummy prompt',
//     function:  'dummy function',
//     console: 'dummy console',
//     winner: 'dummy winner',
//     completedAlgos: {},
//     totalRows: 0,
//     test_cases: [],
//     username: '',
//     userFxn: '',
//     time: '',
//     algoID: '',
//     algoName: '',
//     algoStart: FALSE,
//     algoPrompt: '',
//     endGame: FALSE,
// };